# -*- coding: utf-8 -*-
"""Programming_Assingment3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1utEF-ys9daO6lGWzqWGr1GgHEJbxsvFw

**1.	Write a Python Program to Check if a Number is Positive, Negative or Zero?**
"""

num = float(input("Enter the number to be checked: "))

if num == 0:
  print("The number is Zero")
elif num > 0:
  print("The number is Positive")
else:
  print("The number is Negative")

"""**2. Write a Python Program to Check if a Number is Odd or Even?**"""

num = float(input("Enter the number to be checked: "))

if num/2 == 0:
  print("The number is Even Number")
else:
  print("The number is Odd Number")

"""**3. Write a Python Program to Check Leap Year?**"""

year = int(input("Enter the year: "))

if year%400 == 0 and year%100 == 0:
  print(f"The given year {year} is a leap year")
elif year%4 == 0 and year%100 != 0:
  print(f"The given year {year} is a leap year")
else:
  print(f"The given year {year} is not a leap year")

"""**4. Write a Python Program to Check Prime Number?**"""

num = int(input("Enter the number to be checked: "))

if num == 1:
  print("The number is not prime number")
elif num > 1:
  for i in range(2, num):
    if num%i == 0:
      print("The number is not prime number")
      break
  else:
     print("The number is a prime number")
else:
  print("The number is not prime number")

"""**5. Write a Python Program to Print all Prime Numbers in an Interval of 1-10000?**"""

for num in range(2, 10001):
  for i in range(2, num):
    if num%i == 0:
      break
  else:
     print(num)